/**
 * Dynamic XML sitemap — auto-generated by Next.js 13+ App Router.
 * Includes all static pages + every product and blog from the database.
 *
 * GET /sitemap.xml
 */
import { connectDB } from "@/server/db/mongoose";
import Product from "@/server/models/Product";
import BlogPost from "@/server/models/Blog";
import Category from "@/server/models/Category";

const BASE_URL = process.env.NEXT_PUBLIC_SITE_URL || "https://foodvilleindia.com";

export default async function sitemap() {
  // ── Static pages ────────────────────────────────────────────────────────
  const staticPages = [
    { url: BASE_URL, lastModified: new Date(), changeFrequency: "daily", priority: 1.0 },
    { url: `${BASE_URL}/shop`, lastModified: new Date(), changeFrequency: "daily", priority: 0.9 },
    { url: `${BASE_URL}/blogs`, lastModified: new Date(), changeFrequency: "weekly", priority: 0.7 },
    { url: `${BASE_URL}/bulk-order`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.6 },
    { url: `${BASE_URL}/franchise`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.6 },
    { url: `${BASE_URL}/why-choose-us`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.5 },
    { url: `${BASE_URL}/privacy-policy`, lastModified: new Date(), changeFrequency: "yearly", priority: 0.3 },
    { url: `${BASE_URL}/terms-and-conditions`, lastModified: new Date(), changeFrequency: "yearly", priority: 0.3 },
    { url: `${BASE_URL}/refund-policy`, lastModified: new Date(), changeFrequency: "yearly", priority: 0.3 },
    { url: `${BASE_URL}/shipping-policy`, lastModified: new Date(), changeFrequency: "yearly", priority: 0.3 },
  ];

  // ── Dynamic pages from database ─────────────────────────────────────────
  try {
    await connectDB();

    const [products, blogs, categories] = await Promise.all([
      Product.find({ isActive: true }, { slug: 1, updatedAt: 1 }).lean(),
      BlogPost.find({}, { slug: 1, updatedAt: 1 }).lean(),
      Category.find({}, { slug: 1, updatedAt: 1 }).lean(),
    ]);

    const productPages = products.map((p) => ({
      url: `${BASE_URL}/product/${p.slug}`,
      lastModified: p.updatedAt || new Date(),
      changeFrequency: "weekly",
      priority: 0.8,
    }));

    const blogPages = blogs.map((b) => ({
      url: `${BASE_URL}/blogs/${b.slug}`,
      lastModified: b.updatedAt || new Date(),
      changeFrequency: "monthly",
      priority: 0.6,
    }));

    const categoryPages = categories.map((c) => ({
      url: `${BASE_URL}/category/${c.slug}`,
      lastModified: c.updatedAt || new Date(),
      changeFrequency: "weekly",
      priority: 0.75,
    }));

    return [...staticPages, ...productPages, ...blogPages, ...categoryPages];
  } catch {
    // If database is unavailable during build/ISR, return static pages only.
    return staticPages;
  }
}
